---
- name: Include generic tasks
  include_tasks: generic.yaml
  tags: [generic]

- name: Include packages tasks
  include_tasks: packages.yaml
  tags: [packages]

- name: Include services tasks
  include_tasks: services.yaml
  tags: [services]
