---
- name: Packages | Install basic packages
  ansible.builtin.apt:
    pkg: "{{ apt_packages }}"
    state: present
    update_cache: true
  tags: [install-packages]

######################################################################
# Golang
######################################################################

######################################################################
# GoLand
######################################################################
- name: Paths | Create GoLand target directory
  ansible.builtin.file:
    path: "{{ goland_install_dir }}"
    owner: root
    group: root
    mode: '0755'
  tags: [install-goland]

- name: Packages | Download and install GoLand
  ansible.builtin.unarchive:
    src: "{{ goland_download_url }}"
    dest: "{{ goland_install_dir }}"
    remote_src: true
  tags: [install-goland]

- name: Paths | Create goland symlink
  ansible.builtin.file:
    src: "{{ goland_install_dir }}/bin/goland.sh"
    dest: /usr/bin/goland
    state: link
    owner: root
    group: root
  tags: [install-goland]

######################################################################
# Docker and Docker-compose
######################################################################
- name: Keys | Add docker's apt repository GPG key
  ansible.builtin.apt_key:
    url: "{{ docker_distfiles_url }}/gpg"
    keyring: "{{ apt_repo_keyfile_path }}"
    state: present
  tags: [install-docker]

- name: Repositories | Add docker's apt repository
  ansible.builtin.apt_repository:
    repo: "{{ apt_repo_source }}"
    state: present
  tags: [install-docker]

- name: Packages | Install docker packages
  ansible.builtin.apt:
    pkg: "{{ apt_docker_packages }}"
    state: present
    update_cache: true
  notify: start docker
  tags: [install-docker]

- name: Registers | Check docker-compose executable exists
  ansible.builtin.stat:
    path: /usr/local/bin/docker-compose
  register: docker_compose_check
  tags: [install-docker]

- name: Packages | Install docker-compose
  block:
    - name: Packages | Download and install docker-compose
      ansible.builtin.get_url:
        url: "{{ docker_compose_url }}"
        dest: /usr/local/bin/docker-compose
        owner: root
        group: root
        mode: '0755'
  when: not docker_compose_check.stat.exists
  tags: [install-docker]

######################################################################
# Vagrant and VirtualBox
######################################################################

######################################################################
# Telegram
######################################################################
