---
- name: Paths | Create postgres-primary volume directory
  ansible.builtin.file:
    dest: "{{ postgres_volume_dir_prefix }}-primary"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: [postgres]

- name: Docker Networks | Create network for Postgres containers
  community.general.docker_network:
    name: postgres
  tags: [postgres]

- name: Systemd | Create unit-file for Postgres primary from template
  ansible.builtin.template:
    src: systemd-postgres.j2
    dest: /etc/systemd/system/postgres-primary.service
    owner: root
    group: root
    mode: '0644'
  tags: [postgres]

- name: Services | Enable and start Postgres primary service
  ansible.builtin.systemd:
    name: postgres-primary
    state: started
    daemon-reload: True
    enabled: True
  tags: [postgres]
