---
home_subdirs:
  - Documents
  - Downloads
  - Music
  - Temp
  - Video

apt_packages:
  - jq                             # command line JSON processor
  - gcc
  - vlc                            # multimedia player
  - curl
  - make
  - gnupg
  - iotop                          # simple top-like IO monitor
  - deluge
  - okular                         # universal document viewer
  - firefox
  - sysstat                        # system performance tools
  - openvpn
  - network-manager-openvpn
  - openvpn-systemd-resolved
  - yakuake                        # quake-style dropdown terminal emulator
  - gwenview                       # image viewer
  - krusader                       # twin-panel file manager
  - audacious                      # audio player
  - lsb-release
  - ca-certificates
  - build-essential
  - chromium-browser
  - chromium-browser-l10n
  - chromium-codecs-ffmpeg-extra

non_apt_install_root: /opt

docker_version: 20.10.17
docker_compose_version: 2.7.0
docker_compose_url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-{{ ansible_architecture }}"

docker_distfiles_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
apt_repo_keyfile_path: /etc/apt/trusted.gpg.d/docker.gpg
apt_repo_source: "deb [arch=amd64 signed-by={{ apt_repo_keyfile_path }}] {{ docker_distfiles_url }} {{ ansible_distribution_release }} stable"

apt_docker_version: "5:{{ docker_version }}~3-0"
apt_docker_packages:
  - "docker-ce={{ apt_docker_version }}~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}"
  - "docker-ce-cli={{ apt_docker_version }}~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}"
  - containerd.io
  - docker-compose-plugin

golang_version: 1.19.2
golang_download_url: "https://go.dev/dl/go{{ golang_version }}.linux-amd64.tar.gz"
golang_install_dir: "{{ non_apt_install_root }}/go-{{ golang_version }}"

golangci_lint_version: 1.50.0
golangci_lint_download_url: "https://github.com/golangci/golangci-lint/releases/download/v{{ golangci_lint_version }}/golangci-lint-{{ golangci_lint_version }}-linux-amd64.tar.gz"

goland_version: 2022.2
goland_download_url: "https://download.jetbrains.com/go/goland-{{ goland_version }}.tar.gz"
goland_install_dir: "{{ non_apt_install_root }}/GoLand-{{ goland_version }}"

telegram_download_url: "https://telegram.org/dl/desktop/linux"
telegram_install_dir: "{{ non_apt_install_root}}/Telegram"

princexml_download_url: https://www.princexml.com/download/prince_14.3-1_ubuntu20.04_amd64.deb

####
# Services variables
####

postgres_volume_dir_prefix: /opt/docker/postgres