COUNT = 1
HOST = "vg"
BOX_IMAGE = ENV["BOX_IMAGE"] || "ubuntu/focal64"

Vagrant.configure("2") do |config|
    (1..COUNT).each do |i|
        config.ssh.insert_key = false
        # config.ssh.private_key_path = "#{Dir.home}/.ssh/id_rsa"
        config.vm.define "#{HOST}#{i}" do |subconfig|
            subconfig.vm.box = BOX_IMAGE
            subconfig.vm.network :private_network, ip: "192.168.56.#{10 + i}"
            subconfig.vm.hostname = "#{HOST}#{i}"

            subconfig.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "512"]
                vb.customize ["modifyvm", :id, "--cpus", "1"]
                vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
                vb.customize ["modifyvm", :id, "--nestedpaging", "on"]
                vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
                vb.name = "#{HOST}#{i}"
            end

            ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
            subconfig.vm.provision "shell", inline: <<-SHELL
                sudo echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
            SHELL

            (1..COUNT).each do |i|
                subconfig.vm.provision "shell", inline: <<-SHELL
                    sudo echo "192.168.56.#{10 + i} #{HOST}#{i}" | sudo tee -a /etc/hosts
                SHELL
            end
        end
    end
end